name: logServerData

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.5.0'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          node data/my_script.js

